# Generated by Django 3.2.12 on 2022-03-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.CharField(default='', max_length=1020),
        ),
    ]
